title: Alpine.js
logo: tech/alpine.svg
link: 'https://alpinejs.dev/'
color: '#FFFFFF'
updated_by: 1cfd3a17-8ebc-4c6e-a6a7-74b95b4fcd53
updated_at: 1642763669
blueprint: technology
white: false
badge_color: '#77C1D2'
