title: CSS
logo: tech/CSS3.svg
link: 'https://developer.mozilla.org/de/docs/Learn/Getting_started_with_the_web/CSS_basics'
color: '#FFFFFF'
updated_by: 1cfd3a17-8ebc-4c6e-a6a7-74b95b4fcd53
updated_at: 1642763720
blueprint: technology
white: true
badge_color: '#264DE4'
