title: StoryBook
logo: tech/storybook.svg
link: 'https://storybook.js.org/'
color: '#FFFFFF'
updated_by: 1cfd3a17-8ebc-4c6e-a6a7-74b95b4fcd53
updated_at: 1642766521
blueprint: technology
white: true
badge_color: '#FF4785'
