title: TypeScript
logo: tech/TypeScript.svg
link: 'https://www.typescriptlang.org/'
color: '#3178C6'
updated_by: 1cfd3a17-8ebc-4c6e-a6a7-74b95b4fcd53
updated_at: 1642766182
blueprint: technology
white: true
