title: ViteJs
logo: tech/vite.svg
link: 'https://vitejs.dev/'
color: '#FFFFFF'
updated_by: 1cfd3a17-8ebc-4c6e-a6a7-74b95b4fcd53
updated_at: 1642766352
blueprint: technology
white: true
badge_color: '#A94DFE'
