title: Vue.js
logo: tech/vue.svg
link: 'https://v3.vuejs.org/'
color: '#FFFFFF'
updated_by: 1cfd3a17-8ebc-4c6e-a6a7-74b95b4fcd53
updated_at: 1642766283
blueprint: technology
white: true
badge_color: '#42B983'
