name: Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  X_APPWRITE_BASE_PATH: Monday
  X_APPWRITE_KEY: Monday
  X_APPWRITE_PROJECT: Mondy
jobs:
  build:
    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Format Code
        run: npm run format

      - name: Typescript
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test:unit
